name: Docker Build Check

on:
  workflow_dispatch:
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - uses: docker/build-push-action@v3
        with:
          push: false
          platforms: linux/amd64
          tags: ziinc/crawldis:local
          # caching
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Run Pytest
        uses: addnab/docker-run-action@v3
        with:
          image: ziinc:crawldis:local
          options: |
            -v ${{ github.workspace }}/init.json:/app/bin/init.json
            -v ${{ github.workspace }}/export:/app/bin/export 
            -e CRAWLDIS_CONFIG_FILE=init.json
      - name: Export to JSONL check
        run: grep -Fxq "How to Generate Dynamic Pages for Docusaurus" export/posts.jsonl